### ISSUE TITLE
Middle click on OS X

### ISSUE THREAD

**Issue by bertfreudenberg** [livingcomputermuseum/ContrAlto#11]
ContrAlto works fine on my MacBook using mono. Awesome!
I cannot get the middle mouse button to work, though.
I installed MiddleClick (https://www.howtogeek.com/267782/how-to-add-a-middle-click-to-your-macs-trackpad/) and it works fine in other apps.
But in ContrAlto, it seems to act only as the first mouse button. I'm testing in Smalltalk-76 from xmsmall.dsk.
Any advice?

**Comment by livingcomputermuseum** [comment]
Thanks for the report!  I'll take a look at this soon.  If you happen to have a USB mouse to try, it would be interesting to know if that exhibits the same problems.



________________________________

**Comment by bertfreudenberg** [comment]
I tried with MagicPrefs and that works fine. http://magicprefs.com

So probably it’s not a problem with ContrAlto but with the MiddleClick tool.
