### ISSUE TITLE
Exception being raised

### ISSUE THREAD

**Issue by ruimaranhao** [livingcomputermuseum/ContrAlto#2]
I've installed the software in a Parallels VM running Windows 7 64bit. I am not being able to start the Xerox Alto Emulator because of an exception being raised (empty Array). 

Any idea what is going on?

**Comment by livingcomputermuseum** [comment]
Try installing .NET 4.6 – this will be addressed in the next release, but until then that should work around the problem.

Thanks!
Josh

**Comment by ruimaranhao** [comment]
Thanks. I will give it a try.
